### ISSUE TITLE
モバイル向け画面でClickしたさいDrawerが閉じない

### ISSUE THREAD

**Issue by k2wanko** [firebasejp/website#7]
<img width="432" alt="2017-12-07 18 13 43" src="https://user-images.githubusercontent.com/4466222/33707346-6d96585a-db7a-11e7-8574-dc953f6df76a.png">

**Comment by Yatima-Kagurazaka** [comment]
ふむ，Chrome @ Pixelとか， devtools上とかでは問題ないですなぁ

**Comment by k2wanko** [comment]
MacのChromeです
